const tr = {
  name: "نام",
  enter_name: "نام خود را وارد کنید",
  family: "نام خانوداگی",
  enter_family: "نام خانوادگی خود را وارد کنید",
  mobile: "شماره موبایل",
  enter_mobile: "شماره موبایل خود را وارد کنید",
  do_u_have_Account: "حساب کاربری دارید؟",
  u_dont_have_Account: "حساب کاربری ندارید؟",
  login: "ورود",
  register: "ثبت نام",
  register_in_web: "ثبت نام کنید",
  welcome_to_my_ravanhesab: "به روانحساب من خوش آمدید",
  loadingText: "در حال بارگذاری...",
  send_login_code: "ارسال کد تایید",
  code_sended_to_numer: "کد ارسال شده به شماره ",
  ra: "را ",
  number_in_family_name_not_allowed: "استفاده از عدد در نام خانوادگی مجاز نیست.",
  number_in_name_not_allowed: "استفاده از عدد در نام مجاز نیست.",
  verify_number: "تایید شماره",
  enter: "وارد کنید",
  back: "بازگشت",
  enter_a_valid_phone_number: "یک شماره تماس معتبر وارد کنید.",
  add_to_card:"افزودن به سبد خرید",
  receiving_data: "در حال دریافت اطلاعات...",

}
export default tr;